/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import NapakalakiGame.BadConsequence;
import NapakalakiGame.NumericBadConsequence;
import NapakalakiGame.SpecificBadConsequence;
import java.util.stream.Collectors;

/**
 *
 * @author guille
 */
public class PendingBadConsequenceView extends javax.swing.JPanel {

    /**
     * Creates new form PendingBadConsequenceView
     */
    public PendingBadConsequenceView() {
        initComponents();
    }
    
    /**
     * Attributes
     */
    BadConsequence pendingBadModel;
    
    /**
     * Init pendingBadModel
     * @param nModel 
     */
    public void setPendingBadConsequence(BadConsequence nModel){
        pendingBadModel = nModel;
        
        if (pendingBadModel instanceof NumericBadConsequence) {
            jL_visible.setText("Lose " + Integer.toString(((NumericBadConsequence) pendingBadModel).getNVisibleTreasures()) + " visible treasures");
            jL_hidden.setText("Lose " + Integer.toString(((NumericBadConsequence) pendingBadModel).getNHiddenTreasures()) + " hidden treasures");
        }
        else if (pendingBadModel instanceof SpecificBadConsequence){
            jL_visible.setText("Lose these visibles: " + ((SpecificBadConsequence)pendingBadModel).getSpecificVisibleTreasures().stream().map(Object::toString).collect(Collectors.joining(", ")));
            jL_hidden.setText("Lose these hidden: "+ ((SpecificBadConsequence)pendingBadModel).getSpecificHiddenTreasures().stream().map(Object::toString).collect(Collectors.joining(", ")));
        }
        
        repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jL_visible = new javax.swing.JLabel();
        jL_hidden = new javax.swing.JLabel();

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jL_visible)
                    .addComponent(jL_hidden))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jL_visible)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jL_hidden)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jL_hidden;
    private javax.swing.JLabel jL_visible;
    // End of variables declaration//GEN-END:variables
}
