/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import NapakalakiGame.Treasure;

/**
 *
 * @author guille
 */
public class TreasureView extends javax.swing.JPanel {

    /**
     * Creates new form TreasureView
     */
    public TreasureView() {
        initComponents();
    }
    
    /**
     * Attributes
     */
    
    Treasure treasureModel;
    
    /**
     * Initialize treasure model
     * @param nModel 
     */
    public void setTreasure(Treasure nModel){
        treasureModel = nModel;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jL_name = new javax.swing.JLabel();
        jL_bonus = new javax.swing.JLabel();
        jL_tKind = new javax.swing.JLabel();

        jL_name.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        jL_name.setText(treasureModel.getName());

        jL_bonus.setText("Bonus: " + Integer.toString(treasureModel.getBonus()));

        jL_tKind.setText("Treasure kind: " + treasureModel.getType().toString());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jL_name)
                    .addComponent(jL_bonus, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jL_tKind, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jL_name)
                .addGap(18, 18, 18)
                .addComponent(jL_bonus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jL_tKind)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jL_bonus;
    private javax.swing.JLabel jL_name;
    private javax.swing.JLabel jL_tKind;
    // End of variables declaration//GEN-END:variables
}
