/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import NapakalakiGame.Treasure;
import java.awt.Color;

/**
 *
 * @author guille
 */
public class TreasureView extends javax.swing.JPanel {

    /**
     * Creates new form TreasureView
     */
    public TreasureView() {
        initComponents();
        selected = false;
        setBackground(Color.CYAN);
        setOpaque(false);
    }
    
    /**
     * Attributes
     */
    
    Treasure treasureModel;
    boolean selected;
    
    /**
     * Initialize treasure model
     * @param nModel 
     */
    public void setTreasure(Treasure nModel){
        treasureModel = nModel;
        jL_name.setText("<html><body>" + treasureModel.getName() + "<html><body>");
        jL_bonus.setText(Integer.toString(treasureModel.getBonus()));
        jL_kind.setText(treasureModel.getType().toString());
        repaint();
        revalidate(); //TODO: CHECK: Not sure if this is necessary
    }
    
    /**
     * @return if the treasure is selected or not
     */
    public boolean isSelected(){
        return selected;
    }
    
    /**
     * @return tesoro modelo de la vista 
     */
    public Treasure getTreasure(){
        return treasureModel;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jL_name = new javax.swing.JLabel();
        jL_bonus = new javax.swing.JLabel();
        jL_kind = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        jL_name.setText("jLabel1");

        jL_bonus.setText("jLabel1");

        jL_kind.setText("jLabel2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jL_kind, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jL_name, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jL_bonus))
                .addGap(15, 15, 15))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jL_name, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jL_bonus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jL_kind)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        if (selected) 
            setOpaque(false);
        else
            setOpaque(true);
        
        selected = !selected;
        repaint();
    }//GEN-LAST:event_formMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jL_bonus;
    private javax.swing.JLabel jL_kind;
    private javax.swing.JLabel jL_name;
    // End of variables declaration//GEN-END:variables
}
